# Generated by Django 5.0.6 on 2024-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_profile_project_members_bonus_members_salary_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
